### ISSUE TITLE
How to pass MDX props into code blocks?

### ISSUE THREAD

**Issue by mmathys** [rehypejs/rehype-highlight#27] opened 2023-07-21 14:29 UTC
### Initial checklist

- [x] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Latest

### Steps to reproduce

Write a code block passing a prop

```
Hello {props.name}
```

and instantiate it with

```
<Element name="World" />
```

### Expected behavior

The code should say

```
Hello World
```

### Actual behavior

The code says

```
Hello {props.name}
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Vite

**Comment by ChristianMurphy** [comment] 2023-07-21 14:32
Duplicate of https://github.com/orgs/mdx-js/discussions/2288

**Closed by ChristianMurphy** 2023-07-21 14:32 UTC
Labels: 🤞 phase/open
